import type { Metadata } from 'next';

import './styles/globals.scss';
import { inter } from './ui/fonts';

export const metadata: Metadata = {
  title: 'Gallery site',
  // description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
